### analysis of dissimilarity index ###
### values came from bitwise.dist(geno,missing_match= FALSE,scale_missing = FALSE) in poppr() ###
### genotypes are from vcf file generated by samtools, 
### and include missing data. (5% missing data = "95perc"; 3372 loci)

df2 = read.csv("data/DissimilarityDist_clones_95perc.csv.gz")
pdf("output/histogram_dissimilarity.pdf")
hist(df2$d,col="grey",breaks=1000,xlab="DissimilarityPerc",main = "FF")
segments(threshold,0,threshold,1000,"red")
hist(df2$d,col="grey",breaks=1000,ylim=c(0,100),xlim=c(0,0.2),xlab="DissimilarityPerc",main = "")
segments(threshold,0,threshold,1000,"red")
dev.off()
